---
- name: Uninstall Docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: absent
    purge: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Remove all file in /var/lib/docker
  file:
    path: /var/lib/docker
    state: absent

- name: Remove all file in /etc/docker
  file:
    path: /etc/docker
    state: absent