---
- name: UBUNTU - Uninstall Docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: absent
    purge: yes

- name: UBUNTU - Remove useless packages from the cache
  apt:
    autoclean: yes

- name: UBUNTU - Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: UBUNTU - Remove docker-compose
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/docker-compose
    - /usr/bin/docker-compose

- name: UBUNTU - Remove all file in /var/lib/docker
  file:
    path: /var/lib/docker
    state: absent

- name: UBUNTU - Remove all file in /etc/docker
  file:
    path: /etc/docker
    state: absent