---
- name: CENTOS - Upgrade Operating System
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: os_upgrade_info

- name: CENTOS - Restart Node If Operating System Upgraded
  shell: sleep 5 && shutdown -r now "Operating System Upgrade Triggered" 
  args:
    warn: false
  async: 1
  poll: 0    
  when: os_upgrade_info.changed

- name: CENTOS - Wait For Node to Be Ready If Operating System Upgraded
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 600
  when: os_upgrade_info.changed

- name: CENTOS - Install Required Packages
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'curl']
    update_cache: yes
    state: present